### ISSUE TITLE
Needs to work on Firefox.

### ISSUE THREAD

**Issue by taigrr** [taigrr/searchBGon#1]
I haven't used Google Chrome in a while now, and I really miss this extension, so I'll be porting it to Firefox.

**Comment by taigrr** [comment]
Done, see here: https://addons.mozilla.org/en-US/firefox/addon/searchbegone/

**Comment by ioc2e3** [comment]
> 完成，請參閱： https: [//addons.mozilla.org/en-US/firefox/addon/searchbegone/](https://addons.mozilla.org/en-US/firefox/addon/searchbegone/)

That ...

It's been 4 years since the last update

.

**Comment by taigrr** [comment]
Do you need something specific? it still works on firefox I use it daily...

@ioc2e3

**Comment by ioc2e3** [comment]
> 您需要一些具體的東西嗎？它仍然可以在 Firefox 上運行，我每天都使用它...

That ...

searchBGon has not been updated ...

So worried about what's going to happen .

**Comment by taigrr** [comment]
Nothing to worry about. 

If Firefox stops supporting Manifestv2, the Manifestv3 version is ready. 

For now, Firefox is keeping Manifestv2 so no updates are required.
